// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import ()

type PageView struct {
	PageID string
	Views  int32
}

type PageViewsIp struct {
	PageID string
	Ip     string
}
